#%RAML 1.0 NamedExample
- systemID: "1"
  globalID: "0031U000007abF4QAI"
  governmentID: "212-33-1966"
  issuingGovernment: "USA-DC"
  city: "Austin"
  email: "rose@edge.com"
  streetAddress: "313 Constitution Place"
  country: "US"
  postalCode: "78767"
  lastName: "Gonzalez"
  firstName: "Rose"
  region: "TX"
  telephone: "(512) 757-6000"
- systemID: "2"
  globalID: "0031U000007abF5QAI"
  governmentID: "016-06-0266"
  issuingGovernment: "USA-MA"
  city: "Austin"
  email: "sean@edge.com"
  streetAddress: "312 Constitution Place"
  country: "US"
  postalCode: "78767"
  lastName: "Forbes"
  firstName: "Sean"
  region: "TX"
  telephone: "(512) 757-6000"
- systemID: "3"
  globalID: "0031U000007abF6QAI"
  governmentID: "019-09-0992"
  issuingGovernment: "USA-MD"
  city: "Burlington"
  email: "jrogers@burlington.com"
  streetAddress: "525 S. Lexington Ave"
  country: "USA"
  postalCode: "27215"
  lastName: "Rogers"
  firstName: "Jack"
  region: "NC"
  telephone: "(336) 222-7000"