pipeline {
  agent any

  //get AWS MySQL database username and password from Jenkins Credentials
  environment {  
    AWS_RDS_PERS = credentials('PS_Team_MySQL') 
  }
  
  tools{
      maven 'Maven_Local3.6.2'
    }
  stages {
    //---------------------------------------------------
    //Automated Testing with MUnit
    //---------------------------------------------------
    stage('Test') {
        steps {
            sh '/usr/local/bin/mvn -f mysql-deploy-gc-api/pom.xml clean test'
        }
        post {
             success {
                echo "...MUnit completed successfully" 
             } 
            unsuccessful { 
                echo "^^^^^ MUnit Automated test FAILED ^^^^^" 
            }
        }
        
    }
    //---------------------------------------------------
    //Deploy to GovCloud
    //---------------------------------------------------
    stage('Deploy Government Cloud') {
      //environment {  MYSQL_CREDENTIALS = credentials('AWS_RDS_PERS')
      // add Connected App Client Id and Client Secret to the Jenkins credentials and 
      //   pass the values as parameters to the deploy.sh to make it more reusable
      //   GC_CA GovCloud_ConnectedApp
      
      steps {
        //get GovCloud Connected App Client_Id and Client_Secret from Jenkins Credentials
        withCredentials([[
          $class: 'UsernamePasswordMultiBinding',
          credentialsId: 'GC_CA_CREDENTIALS',
          usernameVariable: 'GC_CA_CREDENTIALS_USR',
          passwordVariable: 'GC_CA_CREDENTIALS_PSW', ]]) 
         {
           //sh '. ./deploy.sh'
           sh 'bash ./mysql-deploy-govcloud-api/govCloudDeploy.sh ${GC_CA_CREDENTIALS_USR} ${GC_CA_CREDENTIALS_PSW} 52.55.148.195 3306 ${AWS_RDS_PERS_USR} ${AWS_RDS_PERS_PSW} People_MySQL'
         }  
      }
      //comment lines begin with double slash, keep this as a reminder
    }
  }
}
