#%RAML 1.0 DataType

properties:
  systemID: string
  globalID: string
  firstName?: string | nil
  middleName?: string | nil
  lastName?: string | nil
  governmentID?: string | nil
  issuingGovernment?: string | nil
  streetAddress?: string | nil
  city?: string | nil
  region?: string | nil
  country?: string | nil
  postalCode?: string | nil
  telephone?: string | nil
  email?: string | nil