pipeline {
  agent any

  environment {  
    ANYPOINT_CREDENTIALS = credentials('Anypoint') 
  }
  
  tools{
      maven 'Maven_Local3.6.2'
    }
  stages {
    //---------------------------------------------------
    //Deploy to Cloudhub, MC
    //---------------------------------------------------
    stage('Deploy CloudHub') {
      environment {  MYSQL_CREDENTIALS = credentials('AWS_RDS_PERS')
      }  
      steps {
        sh '/usr/local/bin/mvn -f mysql-people-git-demo-api/pom.xml clean package deploy -Dmule.username=${ANYPOINT_CREDENTIALS_USR} -Dmule.password=${ANYPOINT_CREDENTIALS_PSW} -Dmysql.host=mysqlaws1.cafcf8elhrnd.us-east-1.rds.amazonaws.com -Dmysql.port=3306 -Dmysql.user=${MYSQL_CREDENTIALS_USR} -Dmysql.password=${MYSQL_CREDENTIALS_PSW} -Dmysql.database=MySQLAWS1 -DmuleDeploy'
      }
      //comment lines begin with double slash, keep this as a reminder
    }
  }
}
